name: "Smart CI Optimizer"
description: "Predicts risk and time, decides to skip CI job"
inputs:
  job:
    description: "The CI job name"
    required: true
    default: "unit-tests"
outputs:
  skip:
    description: "true if CI job should be skipped"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install scikit-learn joblib
      shell: bash

    - name: Run decision engine
      run: python smart-ci-action/run.py ${{ inputs.job }}
      shell: bash
