name: "Smart CI Optimizer"
description: "Predicts risk and time, decides whether to skip a CI job"
inputs:
  job:
    description: "The CI job name"
    required: true
    default: "unit-tests"

outputs:
  skip:
    description: "Whether the CI job should be skipped"
    value: ${{ steps.decision.outputs.skip }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install scikit-learn joblib
      shell: bash

    - name: Run decision engine
      id: decision
      run: python smart-ci-action/run.py ${{ inputs.job }}
      shell: bash
