name: "Smart CI Optimizer"
description: "Predicts CI job risk & duration from commit context and decides skip/partial/full"
inputs:
  job:
    description: "The CI job name"
    required: true
    default: "unit-tests"

outputs:
  skip:
    description: "Whether to skip the job"
    value: ${{ steps.decision.outputs.skip }}
  mode:
    description: "Decision mode: skip | partial | full"
    value: ${{ steps.decision.outputs.mode }}
  risk_prob:
    description: "Predicted probability of failure"
    value: ${{ steps.decision.outputs.risk_prob }}
  predicted_time:
    description: "Predicted job duration (seconds)"
    value: ${{ steps.decision.outputs.predicted_time }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install runtime deps
      shell: bash
      run: pip install scikit-learn joblib requests

    - name: Decision engine
      id: decision
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
      run: python smart-ci-action/run.py ${{ inputs.job }}
