name: Smart CI Optimizer (Advanced)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  decide:
    name: Predict Risk/Time & Decide
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.decision.outputs.skip }}
      mode: ${{ steps.decision.outputs.mode }}
      risk_prob: ${{ steps.decision.outputs.risk_prob }}
      predicted_time: ${{ steps.decision.outputs.predicted_time }}
    steps:
      - uses: actions/checkout@v3
      - name: Smart CI
        id: decision
        uses: ./smart-ci-action
        with:
          job: "integration-tests"
      - name: Upload decision log
        uses: actions/upload-artifact@v4
        with:
          name: decision-log
          path: decision_log.csv

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Lint OK"

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm test

  smoke-tests:
    name: Smoke Tests (run on partial/full)
    needs: decide
    if: needs.decide.outputs.mode != 'skip'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Running smoke tests..."
          # put minimal tests here
          echo "✓ basic startup"
          echo "✓ health endpoint"
          echo "✓ 3-5 quick unit tests"

  heavy-job:
    name: Heavy Integration Job (full only)
    needs: decide
    if: needs.decide.outputs.mode == 'full'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Running heavy integration..."
          sleep 10
          echo "Done"
