name: Smart CI Optimizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  decide:
    name: Predict Risk and Time
    runs-on: ubuntu-latest
    outputs:
      skip-heavy: ${{ steps.decision.outputs.skip }}
    steps:
      - uses: actions/checkout@v3

      - name: Run Smart CI Optimizer
        id: decision
        uses: ./smart-ci-action
        with:
          job: "heavy-job"

      - name: Upload decision log
        uses: actions/upload-artifact@v4
        with:
          name: decision-log
          path: decision_log.csv

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Simulate linting
        run: echo "Lint passed!"

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  heavy-job:
    name: Heavy Integration Job
    needs: decide
    if: needs.decide.outputs.skip-heavy != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run heavy simulation
        run: |
          echo "Running heavy job..."
          sleep 10
          echo "Heavy job done!"
